export default {
  guide: [
    'README',
    {
      type: 'category',
      label: 'Install & connect',
      items: ['intro', 'clients', 'installation'],
    },
    {
      type: 'category',
      label: 'Hands-on tutorials',
      collapsed: false,
      items: [
        'tutorials/install-components',
        'tutorials/codex-dataset',
        'tutorials/archive-and-summarize',
        'tutorials/clean-and-plot',
        'tutorials/claude-analysis',
        'tutorials/choose-storage',
        'tutorials/contribute-plugin',
      ],
    },
    {
      type: 'category',
      label: 'Contribute',
      items: ['contributing', 'authoring', 'plugins'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'marketplace',
        {type: 'autogenerated', dirName: 'mcps'},
      ],
    },
  ],
};
